[package]
name = "visionario_feed"
version = "0.1.0"
authors = ["Journeyman <antisocial@storiepvtride.it>"]

[dependencies]
uuid = "0.5"
clap = "2.24.2"
chrono = "0.3"
log = "0.3.8"
env_logger = "0.4.3"
hyper = "0.10.9"
scraper = "0.4.0"

# http://kracekumar.com/post/153116176705/my-experience-with-rust
[dependencies.rusqlite]
version = "0.12.0"
features = ["chrono"]

[lib]
name="db"
test = false
