[package]
name = "cinema_feed"
version = "0.1.2"
authors = ["Journeyman <antisocial@storiepvtride.it>"]

[dependencies]
uuid = "*"
clap = "*"
chrono = "*"
log = "*"
env_logger = "*"
reqwest = "0.8.4"
scraper = "0.4.0"

# http://kracekumar.com/post/153116176705/my-experience-with-rust
[dependencies.rusqlite]
version = "*"
features = ["chrono"]

[lib]
name="db"
test = false
